import {library} from '@fortawesome/fontawesome-svg-core';
import {FontAwesomeIcon, FontAwesomeLayers} from '@fortawesome/vue-fontawesome';
import {
  faArrowAltCircleDown,
  faArrowCircleRight,
  faArrowLeft,
  faAsterisk,
  faBars,
  faBook,
  faCaretRight,
  faCheck,
  faChevronCircleDown,
  faClone,
  faCodeBranch,
  faCommentAlt,
  faEdit,
  faExclamationCircle,
  faHeart,
  faHome,
  faLanguage,
  faMinus,
  faMinusSquare,
  faNetworkWired,
  faPlus,
  faPlusCircle,
  faPlusSquare,
  faQuestionCircle,
  faRedo,
  faSave,
  faSearch,
  faServer,
  faSignInAlt,
  faSitemap,
  faSyncAlt,
  faTimes,
  faTimesCircle,
  faTools,
  faUndo,
} from '@fortawesome/free-solid-svg-icons';
import {faDiscord, faGithub, faPatreon,} from '@fortawesome/free-brands-svg-icons';

library.add(
  faSave,
  faUndo,
  faRedo,
  faExclamationCircle,
  faPlusCircle,
  faTimes,
  faTimesCircle,
  faChevronCircleDown,
  faAsterisk,
  faPlus,
  faSyncAlt,
  faBook,
  faArrowAltCircleDown,
  faArrowLeft,
  faCaretRight,
  faEdit,
  faCheck,
  faHome,
  faCommentAlt,
  faTools,
  faLanguage,
  faMinus,
  faSitemap,
  faPlusSquare,
  faMinusSquare,
  faNetworkWired,
  faQuestionCircle,
  faBars,
  faCodeBranch,
  faClone,
  faSignInAlt,
  faSearch,
  faServer,
  faHeart,
  faArrowCircleRight,

  faGithub,
  faDiscord,
  faPatreon,
);

const FontAwesome = {
  install(Vue) {
    Vue.component('font-awesome', FontAwesomeIcon);
    Vue.component('font-awesome-layers', FontAwesomeLayers);
  },
};

export default FontAwesome;
